### ISSUE TITLE
Authorization 实现有BUG。

### ISSUE THREAD

**Issue by thynson** [jmjoy/apollo-client#14]
计算签名的时候，URL Path应当是以斜杠开头，而实际计算的时候，调用 `PerformRequest::path()` 得到的路径并不是以斜杠打头。

调试 Rust 的实现时的截图
<img width="560" alt="截屏2024-06-14 16 29 56" src="https://github.com/jmjoy/apollo-client/assets/895964/0537a8cb-3849-42ff-a04c-604a1438f4cd">

最终结果：
```
Error: error occurred when apollo response, status: 401 Unauthorized, body: "{"timestamp":"2024-06-14T16:31:38.588+0800","status":401,"error":"Unauthorized","path":"/configs/e2e-test-app/default/application"}"
```

以下是某 Typescript 版本实现计算签名时带入的值：
<img width="472" alt="截屏2024-06-14 16 34 47" src="https://github.com/jmjoy/apollo-client/assets/895964/07972225-13cf-427f-b550-85eaa372dac9">

**Comment by jmjoy** [comment]
你的apollo server是什么版本？

**Comment by thynson** [comment]
v2.1.2

**Comment by thynson** [comment]
v2.2.0

**Comment by thynson** [comment]
Caused by: 9667da44d8a218f7b4f97705b7102273f5042f53

**Comment by jmjoy** [comment]
谢谢，你有空修复下吗？

**Comment by jmjoy** [comment]
已经在PR中修复：https://github.com/jmjoy/apollo-client/pull/16

需要发版吗？

**Comment by thynson** [comment]
可以稍等我在本地再验证一下

**Comment by thynson** [comment]
验证了没问题。可以考虑把base64的依赖升级一下

**Comment by jmjoy** [comment]
我将所有依赖都更新，并且有些小调整： https://github.com/jmjoy/apollo-client/pull/18

**Comment by jmjoy** [comment]
0.8.0 released.
