### ISSUE TITLE
能否提供暴露请求的header的设置方法或者默认设置header的accept为"text/plain"

### ISSUE THREAD

**Issue by dengzhq** [jmjoy/apollo-client#6]
通过api获取apollo配置时，会如下操作：
```rust
  // Create configuration client.
    let client =
        ApolloConfClientBuilder::new_via_config_service(Url::parse("服务地址")?)?
            .build()?;

    // Request apollo cached configuration api.
    let configuration: Properties = client
        .cached_fetch(CachedFetchRequest {
            app_id: "xxxx".to_string(),
            namespace_name: "application.properties".to_string(),
            ip: Some(IpValue::HostName),
            ..Default::default()
        })
        .await?;
```
这样发起的请求头的如下
```
GET xxxx HTTP/1.1
accept: */*
host: xxx
```
这样会带来一个问题，accept的语义不清晰，`*/*`表示告诉服务端客户端什么样的返回都能hold住，也因此导致返回什么完全看服务端怎么处理。有些公司会自己二次开发apollo服务，一般都是采用spring boot，会做一定的修改和包装。
sprintboot响应体的返回逻辑主要看如下方法：
```java
org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor#writeWithMessageConverters
```
这个就会导致不同的服务端配置的messageConvert不一样，响应体也会不一样。
如果是返回字符串类型，有的会在原来字符串基础上再序列化了一次。从而导致响应返回多了双引号`""`以及`=`被序列化成unicode字符，例如：
redis.timeout=1000 会变成 “redis.timeout\u003d1000“。
然后这一层在经过`text()`的处理，`\u`的`\`会被抹掉，变成u
```
 async fn from_response(response: Response) -> ApolloClientResult<Self> {
        let content = response.text().await?;
        let i = ini::Ini::load_from_str(&content)?;
        Ok(i.section(None::<&'static str>)
            .ok_or(crate::errors::ApolloClientError::EmptyConfiguration)?
            .clone())
    }

```
即最终通过方法拿到的值变成了：
 “redis.timeoutu003d1000“。这个让人没法处理。
归根究底还是accept的问题，看能否解决呢？
解决办法两个：
1、新增提供暴露header的方法
2、加个默认值，明确语义。只处理文本。
```
let mut request_builder = self.client.request(request.method(), url).header(ACCEPT, "text/plain");
```

**Comment by jmjoy** [comment]
https://github.com/jmjoy/apollo-client/blob/9667da44d8a218f7b4f97705b7102273f5042f53/src/conf/mod.rs#L164

https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.default_headers

这个方法可以让你传默认headers吧。

**Comment by dengzhq** [comment]
确实可以，thanks。
