### ISSUE TITLE
Redundant slash in OpenAPI request path 

### ISSUE THREAD

**Issue by hyangjudy** [jmjoy/apollo-client#8]
Hi,

The first slash in `const OPEN_API_PREFIX: &'static str = "/openapi/v1";` is redundant.

Now it results in an invalid path like `/portal//openapi/v1/envs/env/apps/app/clusters/default/namespaces/namespace/items/content`. 

The fix is `const OPEN_API_PREFIX: &'static str = "openapi/v1";`

Could you remove the slash and publish 0.7.5 ? 

Thanks!

**Comment by jmjoy** [comment]
Welcome your PR!

**Comment by hyangjudy** [comment]
> Welcome your PR!

https://github.com/jmjoy/apollo-client/pull/9

**Comment by jmjoy** [comment]
0.7.5 released.
